### ISSUE TITLE
testing for equality

### ISSUE THREAD

**Issue by sje30** [LakeTide/share#2]
Just a quick note about R's failure to note 0.1 * 3 ==3; Julia says the same:

```
julia> 0.1 * 3 == 3
false
```

**Comment by r3tex** [comment]
The problem lies in R's inability to transparently adapt to your precision needs. Sure, you can use GMP or MPFR, and if you're lucky they even have the functions you're looking for like `cosh()`. If I want accuracy in Julia I can switch to arbitrary precision arithmetic, decimal precision, rational numbers, or any number of other formats. I can even include them in complex numbers, arrays, or any arbitrary structs and it will all just work... so for that specific example:
```
julia> Decimal(0.1) * 3 == 0.3
true

julia> 1//10 * 3 == 3//10
true

julia> x = Decimal(1.0)
Decimal(0, 1, 0)
julia> cosh(x) == (ℯ^x + ℯ^-x)/Decimal(2.0) 
true

julia> ℯ^(π*im) ≈ -1
true
```
